export const Languages = [
  { value: 1, label: 'Afaraf' },
  { value: 2, label: 'аҧсуа бызшәа' },
  { value: 3, label: 'avesta' },
  { value: 4, label: 'Afrikaans' },
  { value: 5, label: 'Akan' },
  { value: 6, label: 'አማርኛ' },
  { value: 7, label: 'aragonés' },
  { value: 8, label: 'العربية' },
  { value: 9, label: 'অসমীয়া' },
  { value: 10, label: 'авар мацӀ' },
  { value: 11, label: 'aymar aru' },
  { value: 12, label: 'azərbaycan dili' },
  { value: 13, label: 'башҡорт теле' },
  { value: 14, label: 'беларуская мова' },
  { value: 15, label: 'български език' },
  { value: 16, label: 'Bislama' },
  { value: 17, label: 'bamanankan' },
  { value: 18, label: 'বাংলা' },
  { value: 19, label: 'བོད་ཡིག' },
  { value: 20, label: 'brezhoneg' },
  { value: 21, label: 'bosanski jezik' },
  { value: 22, label: 'Català' },
  { value: 23, label: 'нохчийн мотт' },
  { value: 24, label: 'Chamoru' },
  { value: 25, label: 'corsu' },
  { value: 26, label: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { value: 27, label: 'čeština' },
  { value: 28, label: 'словѣньскъ' },
  { value: 29, label: 'чӑваш чӗлхи' },
  { value: 30, label: 'Cymraeg' },
  { value: 31, label: 'dansk' },
  { value: 32, label: 'Deutsch' },
  { value: 33, label: 'ދިވެހި' },
  { value: 34, label: 'རྫོང་ཁ' },
  { value: 35, label: 'Eʋegbe' },
  { value: 36, label: 'Ελληνικά' },
  { value: 37, label: 'English' },
  { value: 38, label: 'Esperanto' },
  { value: 39, label: 'español' },
  { value: 40, label: 'eesti' },
  { value: 41, label: 'euskara' },
  { value: 42, label: 'فارسی' },
  { value: 43, label: 'Fulfulde' },
  { value: 44, label: 'suomi' },
  { value: 45, label: 'vosa Vakaviti' },
  { value: 46, label: 'føroyskt' },
  { value: 47, label: 'Français' },
  { value: 48, label: 'Frysk' },
  { value: 49, label: 'Gaeilge' },
  { value: 50, label: 'Gàidhlig' },
  { value: 51, label: 'Galego' },
  { value: 52, label: "Avañe'ẽ" },
  { value: 53, label: 'ગુજરાતી' },
  { value: 54, label: 'Gaelg' },
  { value: 55, label: 'هَوُسَ' },
  { value: 56, label: 'עברית' },
  { value: 57, label: 'हिन्दी' },
  { value: 58, label: 'Hiri Motu' },
  { value: 59, label: 'Hrvatski' },
  { value: 60, label: 'Kreyòl ayisyen' },
  { value: 61, label: 'magyar' },
  { value: 62, label: 'Հայերեն' },
  { value: 63, label: 'Otjiherero' },
  { value: 64, label: 'Interlingua' },
  { value: 65, label: 'Bahasa Indonesia' },
  { value: 66, label: 'Interlingue' },
  { value: 67, label: 'Asụsụ Igbo' },
  { value: 68, label: 'ꆈꌠ꒿ Nuosuhxop' },
  { value: 69, label: 'Iñupiaq' },
  { value: 70, label: 'Ido' },
  { value: 71, label: 'Íslenska' },
  { value: 72, label: 'Italiano' },
  { value: 73, label: 'ᐃᓄᒃᑎᑐᑦ' },
  { value: 74, label: '日本語' },
  { value: 75, label: 'basa Jawa' },
  { value: 76, label: 'ქართული' },
  { value: 77, label: 'KiKongo' },
  { value: 78, label: 'Gĩkũyũ' },
  { value: 79, label: 'Kuanyama' },
  { value: 80, label: 'қазақ тілі' },
  { value: 81, label: 'kalaallisut' },
  { value: 82, label: 'ខេមរភាសា' },
  { value: 83, label: 'ಕನ್ನಡ' },
  { value: 84, label: '한국어' },
  { value: 85, label: 'Kanuri' },
  { value: 86, label: 'कश्मीरी' },
  { value: 87, label: 'Kurdî' },
  { value: 88, label: 'коми кыв' },
  { value: 89, label: 'Kernewek' },
  { value: 90, label: 'Кыргызча' },
  { value: 91, label: 'latine' },
  { value: 92, label: 'Lëtzebuergesch' },
  { value: 93, label: 'luganda' },
  { value: 94, label: 'Limburgs' },
  { value: 95, label: 'Lingála' },
  { value: 96, label: 'ພາສາລາວ' },
  { value: 97, label: 'lietuvių kalba' },
  { value: 98, label: 'Kiluba' },
  { value: 99, label: 'latviešu valoda' },
  { value: 100, label: 'fiteny malagasy' },
  { value: 101, label: 'Kajin M̧ajeļ' },
  { value: 102, label: 'te reo Māori' },
  { value: 103, label: 'македонски јазик' },
  { value: 104, label: 'മലയാളം' },
  { value: 105, label: 'Монгол хэл' },
  { value: 106, label: 'मराठी' },
  { value: 107, label: 'bahasa Melayu' },
  { value: 108, label: 'Malti' },
  { value: 109, label: 'ဗမာစာ' },
  { value: 110, label: 'Dorerin Naoero' },
  { value: 111, label: 'Norsk bokmål' },
  { value: 112, label: 'isiNdebele' },
  { value: 113, label: 'नेपाली' },
  { value: 114, label: 'Owambo' },
  { value: 115, label: 'Nederlands' },
  { value: 116, label: 'Norsk nynorsk' },
  { value: 117, label: 'Norsk' },
  { value: 118, label: 'isiNdebele' },
  { value: 119, label: 'Diné bizaad' },
  { value: 120, label: 'chiCheŵa' },
  { value: 121, label: 'occitan' },
  { value: 122, label: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  { value: 123, label: 'Afaan Oromoo' },
  { value: 124, label: 'ଓଡ଼ିଆ' },
  { value: 125, label: 'Ирон æвзаг' },
  { value: 126, label: 'ਪੰਜਾਬੀ' },
  { value: 127, label: 'पाऴि' },
  { value: 128, label: 'Polski' },
  { value: 129, label: 'پښتو' },
  { value: 130, label: 'Português' },
  { value: 131, label: 'Runa Simi' },
  { value: 132, label: 'rumantsch grischun' },
  { value: 133, label: 'Ikirundi' },
  { value: 134, label: 'Română' },
  { value: 135, label: 'Русский' },
  { value: 136, label: 'Ikinyarwanda' },
  { value: 137, label: 'संस्कृतम्' },
  { value: 138, label: 'sardu' },
  { value: 139, label: 'सिन्धी' },
  { value: 140, label: 'Davvisámegiella' },
  { value: 141, label: 'yângâ tî sängö' },
  { value: 142, label: 'සිංහල' },
  { value: 143, label: 'Slovenčina' },
  { value: 144, label: 'Slovenščina' },
  { value: 145, label: 'Gagana faʻa Sāmoa' },
  { value: 146, label: 'chiShona' },
  { value: 147, label: 'Soomaaliga' },
  { value: 148, label: 'Shqip' },
  { value: 149, label: 'српски језик' },
  { value: 150, label: 'SiSwati' },
  { value: 151, label: 'Sesotho' },
  { value: 152, label: 'Basa Sunda' },
  { value: 153, label: 'Svenska' },
  { value: 154, label: 'Kiswahili' },
  { value: 155, label: 'தமிழ்' },
  { value: 156, label: 'తెలుగు' },
  { value: 157, label: 'тоҷикӣ' },
  { value: 158, label: 'ไทย' },
  { value: 159, label: 'ትግርኛ' },
  { value: 160, label: 'Türkmençe' },
  { value: 161, label: 'Wikang Tagalog' },
  { value: 162, label: 'Setswana' },
  { value: 163, label: 'faka Tonga' },
  { value: 164, label: 'Türkçe' },
  { value: 165, label: 'Xitsonga' },
  { value: 166, label: 'татар теле' },
  { value: 167, label: 'Twi' },
  { value: 168, label: 'Reo Tahiti' },
  { value: 169, label: 'ئۇيغۇرچە' },
  { value: 170, label: 'Українська' },
  { value: 171, label: 'اردو' },
  { value: 172, label: 'Ўзбек' },
  { value: 173, label: 'Tshivenḓa' },
  { value: 174, label: 'Tiếng Việt' },
  { value: 175, label: 'Volapük' },
  { value: 176, label: 'Walon' },
  { value: 177, label: 'Wollof' },
  { value: 178, label: 'isiXhosa' },
  { value: 179, label: 'ייִדיש' },
  { value: 180, label: 'Yorùbá' },
  { value: 181, label: 'Saɯ cueŋƅ' },
  { value: 182, label: '中文' },
  { value: 183, label: 'isiZulu' },
];
